import type { Metadata } from "next";
import {  DM_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import DashboardLayout from "./(dashboard)/layout";
import { ThemeProvider } from "@/provider/theme-provider";
const font = DM_Sans({ subsets: ["latin"] })
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ClerkProvider>
    <ThemeProvider
    attribute="class"
    defaultTheme="dark"
    enableSystem
    disableTransitionOnChange
    >
      {children}
     </ThemeProvider>
    </ClerkProvider>
    </body>
    </html>
  );
}
